// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: app/src/main/proto/sparrow.proto at 19:1
package me.bsu.proto;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import java.util.List;
import okio.ByteString;

/**
 * Control message sent between the client and server before data exchange.
 */
public final class Handshake extends Message<Handshake, Handshake.Builder> {
  public static final ProtoAdapter<Handshake> ADAPTER = new ProtoAdapter_Handshake();

  private static final long serialVersionUID = 0L;

  public static final String DEFAULT_UUID = "";

  public static final String DEFAULT_USERNAME = "";

  public static final String DEFAULT_PUBLIC_KEY = "";

  /**
   * A list of features that the sender of the message supports.
   */
  @WireField(
      tag = 1,
      adapter = "me.bsu.proto.Feature#ADAPTER",
      label = WireField.Label.REPEATED
  )
  public final List<Feature> features;

  /**
   * DO NOT CHANGE ANYTHING ABOVE THIS LINE.
   * FILL IN (IF NEEDED)
   */
  @WireField(
      tag = 2,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  public final String uuid;

  @WireField(
      tag = 3,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  public final String username;

  @WireField(
      tag = 4,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  public final String public_key;

  public Handshake(List<Feature> features, String uuid, String username, String public_key) {
    this(features, uuid, username, public_key, ByteString.EMPTY);
  }

  public Handshake(List<Feature> features, String uuid, String username, String public_key, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.features = Internal.immutableCopyOf("features", features);
    this.uuid = uuid;
    this.username = username;
    this.public_key = public_key;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.features = Internal.copyOf("features", features);
    builder.uuid = uuid;
    builder.username = username;
    builder.public_key = public_key;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof Handshake)) return false;
    Handshake o = (Handshake) other;
    return Internal.equals(unknownFields(), o.unknownFields())
        && Internal.equals(features, o.features)
        && Internal.equals(uuid, o.uuid)
        && Internal.equals(username, o.username)
        && Internal.equals(public_key, o.public_key);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (features != null ? features.hashCode() : 1);
      result = result * 37 + (uuid != null ? uuid.hashCode() : 0);
      result = result * 37 + (username != null ? username.hashCode() : 0);
      result = result * 37 + (public_key != null ? public_key.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (features != null) builder.append(", features=").append(features);
    if (uuid != null) builder.append(", uuid=").append(uuid);
    if (username != null) builder.append(", username=").append(username);
    if (public_key != null) builder.append(", public_key=").append(public_key);
    return builder.replace(0, 2, "Handshake{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<Handshake, Builder> {
    public List<Feature> features;

    public String uuid;

    public String username;

    public String public_key;

    public Builder() {
      features = Internal.newMutableList();
    }

    /**
     * A list of features that the sender of the message supports.
     */
    public Builder features(List<Feature> features) {
      Internal.checkElementsNotNull(features);
      this.features = features;
      return this;
    }

    /**
     * DO NOT CHANGE ANYTHING ABOVE THIS LINE.
     * FILL IN (IF NEEDED)
     */
    public Builder uuid(String uuid) {
      this.uuid = uuid;
      return this;
    }

    public Builder username(String username) {
      this.username = username;
      return this;
    }

    public Builder public_key(String public_key) {
      this.public_key = public_key;
      return this;
    }

    @Override
    public Handshake build() {
      return new Handshake(features, uuid, username, public_key, buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_Handshake extends ProtoAdapter<Handshake> {
    ProtoAdapter_Handshake() {
      super(FieldEncoding.LENGTH_DELIMITED, Handshake.class);
    }

    @Override
    public int encodedSize(Handshake value) {
      return Feature.ADAPTER.asRepeated().encodedSizeWithTag(1, value.features)
          + (value.uuid != null ? ProtoAdapter.STRING.encodedSizeWithTag(2, value.uuid) : 0)
          + (value.username != null ? ProtoAdapter.STRING.encodedSizeWithTag(3, value.username) : 0)
          + (value.public_key != null ? ProtoAdapter.STRING.encodedSizeWithTag(4, value.public_key) : 0)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, Handshake value) throws IOException {
      if (value.features != null) Feature.ADAPTER.asRepeated().encodeWithTag(writer, 1, value.features);
      if (value.uuid != null) ProtoAdapter.STRING.encodeWithTag(writer, 2, value.uuid);
      if (value.username != null) ProtoAdapter.STRING.encodeWithTag(writer, 3, value.username);
      if (value.public_key != null) ProtoAdapter.STRING.encodeWithTag(writer, 4, value.public_key);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public Handshake decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: {
            try {
              builder.features.add(Feature.ADAPTER.decode(reader));
            } catch (ProtoAdapter.EnumConstantNotFoundException e) {
              builder.addUnknownField(tag, FieldEncoding.VARINT, (long) e.value);
            }
            break;
          }
          case 2: builder.uuid(ProtoAdapter.STRING.decode(reader)); break;
          case 3: builder.username(ProtoAdapter.STRING.decode(reader)); break;
          case 4: builder.public_key(ProtoAdapter.STRING.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public Handshake redact(Handshake value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
