// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: app/src/main/proto/sparrow.proto at 30:1
package me.bsu.proto;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Integer;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import java.util.List;
import okio.ByteString;

/**
 * A single message.  Can be either public or private.
 */
public final class Tweet extends Message<Tweet, Tweet.Builder> {
  public static final ProtoAdapter<Tweet> ADAPTER = new ProtoAdapter_Tweet();

  private static final long serialVersionUID = 0L;

  public static final Integer DEFAULT_ID = 0;

  public static final String DEFAULT_AUTHOR = "";

  public static final String DEFAULT_CONTENT = "";

  public static final String DEFAULT_RECIPIENT = "";

  public static final String DEFAULT_SENDER_UUID = "";

  /**
   * The unique id of the tweet.  Set by the tweet's author.
   */
  @WireField(
      tag = 1,
      adapter = "com.squareup.wire.ProtoAdapter#INT32",
      label = WireField.Label.REQUIRED
  )
  public final Integer id;

  /**
   * The username of the tweet's author.
   */
  @WireField(
      tag = 2,
      adapter = "com.squareup.wire.ProtoAdapter#STRING",
      label = WireField.Label.REQUIRED
  )
  public final String author;

  /**
   * The text content of the tweet.
   */
  @WireField(
      tag = 3,
      adapter = "com.squareup.wire.ProtoAdapter#STRING",
      label = WireField.Label.REQUIRED
  )
  public final String content;

  /**
   * The username of the recipient.  If set, the message is a private (direct)
   * message.  If not set, the message is a public (broadcast) message.
   */
  @WireField(
      tag = 4,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  public final String recipient;

  /**
   * DO NOT CHANGE ANYTHING ABOVE THIS LINE.
   * FILL IN (IF NEEDED)
   */
  @WireField(
      tag = 5,
      adapter = "com.squareup.wire.ProtoAdapter#STRING",
      label = WireField.Label.REQUIRED
  )
  public final String sender_uuid;

  @WireField(
      tag = 6,
      adapter = "me.bsu.proto.VectorClockItem#ADAPTER",
      label = WireField.Label.REPEATED
  )
  public final List<VectorClockItem> vector_clocks;

  public Tweet(Integer id, String author, String content, String recipient, String sender_uuid, List<VectorClockItem> vector_clocks) {
    this(id, author, content, recipient, sender_uuid, vector_clocks, ByteString.EMPTY);
  }

  public Tweet(Integer id, String author, String content, String recipient, String sender_uuid, List<VectorClockItem> vector_clocks, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.id = id;
    this.author = author;
    this.content = content;
    this.recipient = recipient;
    this.sender_uuid = sender_uuid;
    this.vector_clocks = Internal.immutableCopyOf("vector_clocks", vector_clocks);
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.id = id;
    builder.author = author;
    builder.content = content;
    builder.recipient = recipient;
    builder.sender_uuid = sender_uuid;
    builder.vector_clocks = Internal.copyOf("vector_clocks", vector_clocks);
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof Tweet)) return false;
    Tweet o = (Tweet) other;
    return Internal.equals(unknownFields(), o.unknownFields())
        && Internal.equals(id, o.id)
        && Internal.equals(author, o.author)
        && Internal.equals(content, o.content)
        && Internal.equals(recipient, o.recipient)
        && Internal.equals(sender_uuid, o.sender_uuid)
        && Internal.equals(vector_clocks, o.vector_clocks);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (id != null ? id.hashCode() : 0);
      result = result * 37 + (author != null ? author.hashCode() : 0);
      result = result * 37 + (content != null ? content.hashCode() : 0);
      result = result * 37 + (recipient != null ? recipient.hashCode() : 0);
      result = result * 37 + (sender_uuid != null ? sender_uuid.hashCode() : 0);
      result = result * 37 + (vector_clocks != null ? vector_clocks.hashCode() : 1);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (id != null) builder.append(", id=").append(id);
    if (author != null) builder.append(", author=").append(author);
    if (content != null) builder.append(", content=").append(content);
    if (recipient != null) builder.append(", recipient=").append(recipient);
    if (sender_uuid != null) builder.append(", sender_uuid=").append(sender_uuid);
    if (vector_clocks != null) builder.append(", vector_clocks=").append(vector_clocks);
    return builder.replace(0, 2, "Tweet{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<Tweet, Builder> {
    public Integer id;

    public String author;

    public String content;

    public String recipient;

    public String sender_uuid;

    public List<VectorClockItem> vector_clocks;

    public Builder() {
      vector_clocks = Internal.newMutableList();
    }

    /**
     * The unique id of the tweet.  Set by the tweet's author.
     */
    public Builder id(Integer id) {
      this.id = id;
      return this;
    }

    /**
     * The username of the tweet's author.
     */
    public Builder author(String author) {
      this.author = author;
      return this;
    }

    /**
     * The text content of the tweet.
     */
    public Builder content(String content) {
      this.content = content;
      return this;
    }

    /**
     * The username of the recipient.  If set, the message is a private (direct)
     * message.  If not set, the message is a public (broadcast) message.
     */
    public Builder recipient(String recipient) {
      this.recipient = recipient;
      return this;
    }

    /**
     * DO NOT CHANGE ANYTHING ABOVE THIS LINE.
     * FILL IN (IF NEEDED)
     */
    public Builder sender_uuid(String sender_uuid) {
      this.sender_uuid = sender_uuid;
      return this;
    }

    public Builder vector_clocks(List<VectorClockItem> vector_clocks) {
      Internal.checkElementsNotNull(vector_clocks);
      this.vector_clocks = vector_clocks;
      return this;
    }

    @Override
    public Tweet build() {
      if (id == null
          || author == null
          || content == null
          || sender_uuid == null) {
        throw Internal.missingRequiredFields(id, "id",
            author, "author",
            content, "content",
            sender_uuid, "sender_uuid");
      }
      return new Tweet(id, author, content, recipient, sender_uuid, vector_clocks, buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_Tweet extends ProtoAdapter<Tweet> {
    ProtoAdapter_Tweet() {
      super(FieldEncoding.LENGTH_DELIMITED, Tweet.class);
    }

    @Override
    public int encodedSize(Tweet value) {
      return ProtoAdapter.INT32.encodedSizeWithTag(1, value.id)
          + ProtoAdapter.STRING.encodedSizeWithTag(2, value.author)
          + ProtoAdapter.STRING.encodedSizeWithTag(3, value.content)
          + (value.recipient != null ? ProtoAdapter.STRING.encodedSizeWithTag(4, value.recipient) : 0)
          + ProtoAdapter.STRING.encodedSizeWithTag(5, value.sender_uuid)
          + VectorClockItem.ADAPTER.asRepeated().encodedSizeWithTag(6, value.vector_clocks)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, Tweet value) throws IOException {
      ProtoAdapter.INT32.encodeWithTag(writer, 1, value.id);
      ProtoAdapter.STRING.encodeWithTag(writer, 2, value.author);
      ProtoAdapter.STRING.encodeWithTag(writer, 3, value.content);
      if (value.recipient != null) ProtoAdapter.STRING.encodeWithTag(writer, 4, value.recipient);
      ProtoAdapter.STRING.encodeWithTag(writer, 5, value.sender_uuid);
      if (value.vector_clocks != null) VectorClockItem.ADAPTER.asRepeated().encodeWithTag(writer, 6, value.vector_clocks);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public Tweet decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.id(ProtoAdapter.INT32.decode(reader)); break;
          case 2: builder.author(ProtoAdapter.STRING.decode(reader)); break;
          case 3: builder.content(ProtoAdapter.STRING.decode(reader)); break;
          case 4: builder.recipient(ProtoAdapter.STRING.decode(reader)); break;
          case 5: builder.sender_uuid(ProtoAdapter.STRING.decode(reader)); break;
          case 6: builder.vector_clocks.add(VectorClockItem.ADAPTER.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public Tweet redact(Tweet value) {
      Builder builder = value.newBuilder();
      Internal.redactElements(builder.vector_clocks, VectorClockItem.ADAPTER);
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
